<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="CRAP">
  <xacro:property name="base_width" value="0.5"/>
  <xacro:property name="base_length" value="0.5"/>
  <xacro:property name="base_height" value="0.05"/>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="0.05"/>


  <!-- Define the base link of the robot -->
  
  <link name="base_link">
    <!-- <inertial>
      <mass value="10"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial> -->

    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
          <box size="0.5 0.5 0.05"/>
      </geometry>
    </collision>
  </link>

  <link name="base_link_intertia">
    <inertial>
      <mass value="10"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>
  
  <link name="base_footprint"/>

  <!-- <gazebo reference="base_footprint">
      <turnGravityOff>false</turnGravityOff>
  </gazebo> -->
  <joint name="base_joint_inertia" type="fixed">
    <parent link="base_link"/>
    <child link="base_link_intertia"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- Define the four  wheels -->
  <xacro:include filename="wheel.xacro"/>
  <xacro:wheel name="front_left_wheel" parent="base_link" x="0.25" y="0.25" z = "${-wheel_zoff}" radius = "${wheel_radius}" thickness = "${wheel_width}"/>
  <xacro:wheel name="front_right_wheel" parent="base_link" x="0.25" y="-0.25" z = "${-wheel_zoff}" radius = "${wheel_radius}" thickness = "${wheel_width}"/>
  
  <xacro:include filename="wheel_driven.xacro"/>
  <xacro:wheel_driven name="rear_left_wheel" parent="base_link" x="-0.25" y="0.25" z = "${-wheel_zoff}" radius = "${wheel_radius}" thickness = "${wheel_width}"/>
  <xacro:wheel_driven name="rear_right_wheel" parent="base_link" x="-0.25" y="-0.25" z = "${-wheel_zoff}" radius = "${wheel_radius}" thickness = "${wheel_width}"/>

  <!-- Define the LIDAR sensor -->
  <xacro:include filename="lidar_gazebo.xacro"/>
  <xacro:rplidar prefix="lidar" parent="base_link" x="0" y="0" z="0.1"/>

  <!-- Define the rgbd camera -->
  <xacro:include filename="kinect_gazebo.xacro"/>
  <xacro:kinect_camera prefix="kinect" parent="base_link" x="0.27" y="0" z="0"/>
  
  <!-- Define the imu camera -->
  <xacro:include filename="imu.xacro"/>
  <xacro:imu prefix="imu" parent="base_link" x="-0.2" y="0" z="0.02"/>

  
  <ros2_control name = "GazeboSystem" type = "system">
    <hardware>
        <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware> 
    <joint name="rear_left_wheel_joint">
            <command_interface name="velocity">
                <param name="min">-10</param>
                <param name="max">10</param>
            </command_interface>
            <state_interface name="velocity"/>
            <state_interface name="position"/>
    </joint>
    <joint name="rear_right_wheel_joint">
        <command_interface name="velocity">
            <param name="min">-10</param>
            <param name="max">10</param>
        </command_interface>
        <state_interface name="velocity"/>
        <state_interface name="position"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find CRAP_sim_def)/config/controller.yaml</parameters>
    </plugin>
  </gazebo>



  <!-- <gazebo>
      <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>

      <update_rate>100</update_rate>

      <num_wheel_pairs>1</num_wheel_pairs>

      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>

      <wheel_separation>0.5</wheel_separation>

      <wheel_diameter>0.1</wheel_diameter>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>false</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>

      </plugin>
      

  </gazebo> -->

</robot>