<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="CRAP">
  <xacro:property name="base_width" value="0.265"/>
  <xacro:property name="base_length" value="0.415"/>
  <xacro:property name="base_height" value="0.18"/>

  <xacro:property name="wheel_radius" value="0.051"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="${base_height/2}"/>


  <!-- Define the base link of the robot -->
  
  <link name="base_link">
    <!-- <inertial>
      <mass value="10"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial> -->

    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
          <box size="0.5 0.5 ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="base_link_intertia">
    <inertial>
      <mass value="10"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>
  
  <link name="base_footprint"/>

  <!-- <gazebo reference="base_footprint">
      <turnGravityOff>false</turnGravityOff>
  </gazebo> -->
  <joint name="base_joint_inertia" type="fixed">
    <parent link="base_link"/>
    <child link="base_link_intertia"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- Define the four  wheels -->
  <xacro:include filename="wheel.xacro"/>
  <xacro:wheel name="front_left_wheel" parent="base_link" x="${base_length/2}" y="${(base_width+wheel_width)/2}" z = "${-wheel_zoff}" radius = "${wheel_radius}" thickness = "${wheel_width}"/>
  <xacro:wheel name="front_right_wheel" parent="base_link" x="${base_length/2}" y="${-(base_width+wheel_width)/2}" z = "${-wheel_zoff}" radius = "${wheel_radius}" thickness = "${wheel_width}"/>
  
  <xacro:include filename="wheel_driven.xacro"/>
  <xacro:wheel_driven name="rear_left_wheel" parent="base_link" x="${-base_length/2}" y="${(base_width+wheel_width)/2}" z = "${-wheel_zoff}" radius = "${wheel_radius}" thickness = "${wheel_width}"/>
  <xacro:wheel_driven name="rear_right_wheel" parent="base_link" x="${-base_length/2}" y="${-(base_width+wheel_width)/2}" z = "${-wheel_zoff}" radius = "${wheel_radius}" thickness = "${wheel_width}"/>

  <!-- Define the LIDAR sensor -->
  <xacro:include filename="lidar_gazebo.xacro"/>
  <xacro:rplidar prefix="lidar" parent="base_link" x="0.205" y="0" z="${0.37-base_height/2}"/>

  <!-- Define the rgbd camera -->
  <xacro:include filename="kinect_gazebo.xacro"/>
  <xacro:kinect_camera prefix="kinect2" parent="base_link" x="0.205" y="0" z="${0.26-base_height/2}"/>

  <!-- Define ROS2 control -->
  <xacro:include filename="ros2_control_real.xacro"/>
  <xacro:diffbot_ros2_control name="DiffBot"/>

</robot>